import { NextPage } from 'next'
import Head from 'next/head'
import { Container } from '../styles/pages'

const Home: NextPage = () => {
    return (
        <Container>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>

            <h1>Hello world</h1>
            <p>A new Website in construction.</p>
        </Container>
    )
}

export default Home
